# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='images/%Y/%m')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
