# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('1', '\u901a\u8fc7'), ('2', '\u4e0d\u901a\u8fc7')], default=2, max_length=10),
        ),
    ]
